### PR TITLE
[FIX] behaviors displaying background on widgets 2, 3 ,4 ,5 ,6

### PR DESCRIPTION
**Pull request by Nanomani**
Fix case there is no fanart for item on Widgets (2, 3 ,4 ,5 ,6)  with this logic : 

fanart (yes/no?) => fallback image (yes/no?) => main menu background (yes/no?) => "no picture"

### CODE REVIEW

**Comment by beatmasterRS** [comment]
@semool

**Comment by Nanomani** [comment]
It is finish now :)

This first version change nothing about logic when focus "menu / sub menu" or "slide out" : 

on focus menu/submenu or slide out :  

=> menu have a custom background set (yes/ no?)  => item 1 of widget 1 have fanart (yes/no?)   =>  fallback image is set  =>  ​no background

**Comment by Nanomani** [comment]
to be clear this PR is only a fix about empty fanart so if it is ok for you it can be push in all case :)

**Comment by beatmasterRS** [comment]
Okay, will be merged soon, thanks a lot for your hard work! :)

**Pull request merged**
