### PR TITLE
[Music Playlist OSD] more simple playlist

### PR DESCRIPTION
**Pull request by beatmasterRS**

### CODE REVIEW

**Comment by beatmasterRS** [comment]
@Nanomani what do you think? It's more a basic playlist, that shows only the current playing song and the following songs. I often listen to music in Kodi, but somehow the use of the playlist was never really intuitive. So maybe it's better to use  basic list?

**Comment by Nanomani** [comment]
I never use playlist. It is why i don't understand your need i think. I m not a good user for give my feeling.
Only thing i can say it is less better for my need. I listen only album when it is finish i chose another one.
Or sometimes I decide to listen again the same track. With this it is a bit less easy :)
Perhaps i m not so young ;)

I don't know if you see what i mean. 
But I will make some test with playlist ...

**Comment by Nanomani** [comment]
just to be sure. with this PR it is no longer possible to go back in the playlist with OSD if the song has been read ? right ?

**Comment by beatmasterRS** [comment]
>> just to be sure. with this PR it is no longer possible to go back in the playlist with OSD if the song has been read ? right ?

Exactly, because this playlist doesn't work like a real playlist: 

- If you play a song from an album with 100 songs and switch to music osd, you may not see the arrow, means which song is playing. 
- If you select a song from the playlist, the playlist jumps to the end/top/whatever and does not stay on the selected song
- Whenever you select a song from the playlist, you have to search, cause you dont know what poristion the song in playlist has

This all seems rather unnatural for me... :)

**Comment by Nanomani** [comment]
Sorry I ran out of time. The little that I use the playlists is a happy mess. 
Right there I didn't miss anything using album playback.

That the logic of this PR applies to the reading of albums it is a regression. :/
I'm sure some people will be confused with that.

I hear your arguments but I'm not sure this PR is the best answer.
Or else I didn't understand anything and forgot what I just said :)

**Comment by beatmasterRS** [comment]
But it is also the case that the playlist did not offer a good user experience. If I have 50 songs in the playlist and song 30 is playing, I can't scroll to song 1 without playing song 20, then song 10, then I can see the song. It was never a fully functional playlist, unfortunately....

With the PR you can now only see all the upcoming tracks,that works great. ;)

**Comment by Nanomani** [comment]
> But it is also the case that the playlist did not offer a good user experience. If I have 50 songs in the playlist and song 30 is playing, I can't scroll to song 1 without playing song 20, then song 10, then I can see the song. It was never a fully functional playlist, unfortunately....
> 
> With the PR you can now only see all the upcoming tracks,that works great. ;)

I agree with everything about the playlist.
I can add more. the playlist is a gadget a joke.

but i'm sorry since the skin went into the public domain thinking only about your need is not possible if it has to have consequences on simple aspets which worked fine.

let everything be clear I am nobody and I respect your work. But this PR is a mistake

**Comment by Nanomani** [comment]
@beatmasterRS 
Please make test with Estuary.
User experience is not  the same at all
All seems worked like a true playlist ...

**Comment by beatmasterRS** [comment]
What exactly should i test? Also, I can't find a playlist in the OSD

**Comment by Nanomani** [comment]
> What exactly should i test? 

anything that according to your needs does not seem to work well with AZR
and the playlist. what made you want this PR.

> Also, I can't find a playlist in the OSD

1 - music full screen 

screenshot00012

2 - press "enter" and select "Music Playlist"

screenshot00014

screenshot00015

**Comment by beatmasterRS** [comment]
Please enable debugging, when testing skins. So you can see, that the window/dialog that opens, when you click on the playlist icon in estuary, isn't musicOSD.xml, like in A:Z-R. It's MyPlaylist.xml.

**Comment by beatmasterRS** [comment]
>>anything that according to your needs does not seem to work well with AZR

What do you mean with that? Please describe in more detail

**Comment by Nanomani** [comment]
> Exactly, because this playlist doesn't work like a real playlist:
>
> If you play a song from an album with 100 songs and switch to music osd, you may not see the arrow, means which song is playing.
>
>If you select a song from the playlist, the playlist jumps to the end/top/whatever and does not stay on the selected song
> 
> Whenever you select a song from the playlist, you have to search, cause you dont know what poristion the song in playlist has
>
> This all seems rather unnatural for me... :)

Your words :S

**Comment by Nanomani** [comment]
I have some example too in my side

With AZR (before this PR) :  
when I add albums in queue then all track are not displayed. I can't navigate in all track list

screenshot00019

Same playlist With Estuary : 
All track are displayed. I can navigate in all track list

screenshot00017

**Comment by beatmasterRS** [comment]
It's not the same playlist, not the same xml as you can see from my last posts... So the playlist in musicosd.xml could never have the same functionality as the real playlist in my playlist.xml

**Comment by Nanomani** [comment]
ok it's a huge misunderstanding on my side o_O 
my english doesn't help ...

Sorry, as already said i have a lot to learn
But this is a bad news. This mean there is never a feature "true playlist" like with Estuary ?

**Comment by beatmasterRS** [comment]
Not in the musicOSD I think. Of course we can add a button to the playlist window, then it's the same like in estuary..

**Comment by beatmasterRS** [comment]
Even after years I am still learning new things :D

**Comment by Nanomani** [comment]
> Not in the musicOSD I think. Of course we can add a button to the playlist window, then it's the same like in estuary..

that would be cool and a great start :)

**Comment by beatmasterRS** [comment]
But the playlist, that is shown in the OSD would be obsolete then...

**Comment by Nanomani** [comment]
> But the playlist, that is shown in the OSD would be obsolete then...

no :  for albums, this make the job (with this PR i m not sure, sorry again ...)
yes : for playlist is not usable

in fact "Yes". 

I have no time yet and your skill. Now that I understand better the situation , I will want to change that :D
I have no idea what is the best compromise to have a real playlist and at the same time respect this part of your work :/

**Comment by beatmasterRS** [comment]
Yes, but imho there is no other way to do that...

**Comment by beatmasterRS** [comment]
screenshot00412

**Comment by Nanomani** [comment]
the real compromise is to use "myplaylist.xml" and your design.

Like this : 
(Coded with feet and quickly, just for fun)



use "myplaylist.xml" fix so many things ...

**Comment by beatmasterRS** [comment]
Please provide your code, the i will take a look :)

**Comment by Nanomani** [comment]
What you see is the "playlist" layout adapted to your "music OSD" design. 
I added buttons OSD, hidden others things here and here... 
But the list of tracks is provided by the slightly modified "playlist" layout :D

before : 

screenshot00000

after : 



this is the idea ...

**Pull request merged**
