### PR TITLE
add InProgressTvShows.xsp

### PR DESCRIPTION
**Pull request by semool**
This xsp represent a real InProgressTvShows list

### CODE REVIEW

**Comment by beatmasterRS** [comment]
What's the difference?

**Comment by semool** [comment]
With the xml:
You added a new Series to your Library and set all the Episodes to the state watched. Then they will be listet... that makes no sense.
With the xsp:
Only Series that realy are inprogress are listet.

**Comment by beatmasterRS** [comment]
@semool 

I have now found time and have tried to reproduce this behavior. Please have a look at the following video. For me everything works as it should. Or am I doing something wrong?

Widget: library://video/tvshows/inprogressshows.xml

https://youtu.be/8bj25P-PLqc

**Comment by beatmasterRS** [comment]
Unfortunately, I still cannot reproduce this behavior. Can anyone help?

**Comment by semool** [comment]
Yes in your Video all is fine. Then i think this behaviour is only a problem when using a Emby Server. I have added a series to the Emby Server and set the watched state directly there.
But i dont see a problem with my commit, for movies you are using also custom xsp files. The inprogress Shows is the only one which uses the xml.
And there is no disadvantage with the xsp file i think.

**Comment by beatmasterRS** [comment]
> But i dont see a problem with my commit, for movies you are using also custom xsp files. The inprogress Shows is the only one which uses the xml.
> And there is no disadvantage with the xsp file i think.

You're right, I didn't even think about the fact that a playlist is also used for movies. And if it increases compatibility, why not!? :)

Thanks again :)

**Pull request merged**
