### PR TITLE
[LibreElec] Fix Improve LibreElecSettings MainWindows

### PR DESCRIPTION
**Pull request by Nanomani**
Before : 

- logo is missing
- some *.png are not show
- focus not visible

screenshot00010

screenshot00011

screenshot00013

After : 

screenshot00016

screenshot00018

screenshot00015

### CODE REVIEW

**Comment by Nanomani** [comment]
Need others fix : 

- Wrong colour on focus in right panel for "Connexions,   Bluetooth"
- Font in left panel are a bite too big
- Some little display fiw here and here


screenshot00014

screenshot00018

screenshot00016

**Comment by beatmasterRS** [comment]
Maybe we need to do a rework in this window... I am only using CoreElec and have done this a few month before:

screenshot00029

**Comment by Nanomani** [comment]
I m agree for consistancy :)
my skills end here :D 
I can only test ...

**Comment by beatmasterRS** [comment]
Yeah its absolutely difficult to test... :D We will see :)

**Comment by Nanomani** [comment]
@beatmasterRS, It is not finish. But I think that I can post PR acceptable :) 

screenshot00020

Without your CoreElec layout no chance at all. So thanks :D

**Comment by beatmasterRS** [comment]
Yes, greaaat :) Please be sure to replace the "font13_title" font def that isnt available in AZR :)

**Pull request merged**
