### PR TITLE
[SkinSettings Lightbox] added litebox support

### PR DESCRIPTION
**Pull request by beatmasterRS**

### CODE REVIEW

**Comment by beatmasterRS** [comment]
@Nanomani 

https://github.com/xbmc/repo-scripts/pull/2054

:)

**Comment by Nanomani** [comment]
Thanks for this information ;)

**Comment by Nanomani** [comment]
@beatmasterRS

https://github.com/xbmc/repo-scripts/pull/2054 is merged :D

**Comment by beatmasterRS** [comment]
Great, thanks for the info! :) So we only need colorbox for blur, right? That makes the code easier. Or what do you think?

**Comment by Nanomani** [comment]
> So we only need colorbox for blur, right? That makes the code easier. Or what do you think?

Colorbox is replaced by Litebox.
So Colorbox must be forget. No ?
I understood that Litebox is Colorbox with additional possibilities.
I m wrong ? :)

**Comment by beatmasterRS** [comment]
I thought litebox has less functions than colorbox :D

I meant, that currently we support embuary blur and colorbox blur. But now we dont need embuary helper for blur anymore, scine litebox is faster and has more functions. what do you think?

**Comment by Nanomani** [comment]
It's nice to ask me the question. You knew more than me. :)
Everything I have seen with Colorbox is better in every way.
I see no reason to maintain the confusion with 2 solutions
IMHO embuary helper is no longer needed

**Comment by beatmasterRS** [comment]
Maybe you can take a look at this and test?

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/401

**Pull request closed without merging**
