### PR TITLE
Improve OSD title width

### PR DESCRIPTION
**Pull request by fabricionaweb**
After my last changes, I've notice that without the poster we can use more space for the movie title/episode. 
I did tests with movie and tvshow and I figured out some values that looks good to me.
I just dont know about PVR content, I never used, I know nothing... 

I also improve the conditionals to now take into account the numeric rating as well (stars rating uses more space) 
And I kept the same width for `flagiconsosd` and `flagiconsosdnoicons`. Could be different since `flagiconsosdnoicons` consumes less space, but for now its fine. 

<details>
<summary>Before</summary>

image
image
</details>

<details>
<summary>After</summary>

image
image
</details>

Ps. For episodes there's an auto scroll effect, the rest of `Adventure Time` title will appears in that scroll... Different of the Movie that only has `...`

### CODE REVIEW

**Review by beatmasterRS — COMMENTED** [review]
Looks nice! I also noticed, that we can use more space. Can you integrate that in the code? Because for me the spacing is still the same and and I can't see any code that refers to it. Maybe I have not seen something. :I

The rest works great and PVR I'm still testing.

Thanks for your work, I really appreciate it!

**Comment by fabricionaweb** [comment]
Could not you notice the diffs? Weird... have I did something wrong?

- The changes are only visible for `usethemeNewOSD` (means Matrix and not side one)
- The changes for TV Show are bigger because I created `DefOSDPlayerTVShowTitle` (based on `DefOSDPlayerTitle`)
- The code for TVShow starts in `Includes_OSD.xml:845` and goes until `Includes_OSD.xml:892`
    - https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/39/files#diff-71a84e99dd0497ab741fa4ccb00d8a47402a6e008fdeca217bdf5d94611fcbb8R859-R892
- The code for Movies starts in `Includes_OSD.xml:911` and goes until `Includes_OSD.xml:944`
    - https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/39/files#diff-71a84e99dd0497ab741fa4ccb00d8a47402a6e008fdeca217bdf5d94611fcbb8R911-R944
- The values is `<param name="width" value="..."/>` and the values should change 8 times for each (4 with posters, 4 without posters)

**Comment by beatmasterRS** [comment]
What i meat was, i cant see the changes refering to more space:

screenshot00187

Your other changes i have seen :)

**Comment by fabricionaweb** [comment]
Oh, now I see... I got it, but how can I see that grid system? hehe 
But I guess I know what is this space...

**Comment by beatmasterRS** [comment]
You can enable the grid here:

screenshot00189

**Comment by fabricionaweb** [comment]
It is much better now

image

**Pull request merged**
