### PR TITLE
[Home Header] Improvements "Settings"

### PR DESCRIPTION
**Pull request by Nanomani**
- main menu "settings" display CPU and RAM used

### CODE REVIEW

**Comment by beatmasterRS** [comment]
Just an idea, if we could add also a storage info, what do you think? Then it does not look so lost/little :)

**Comment by Nanomani** [comment]
> Just an idea, if we could add also a storage info, what do you think? Then it does not look so lost/little :)

If you prefer like that ? : 



Why not :) I push a commit for this

**Comment by beatmasterRS** [comment]
Looks good! Ready to merge? :)

**Comment by Nanomani** [comment]
> Looks good! Ready to merge? :)

Yes 👍

**Pull request merged**
