### PR TITLE
[CoreELEC LibreELEC Settings] improvements to settings window

### PR DESCRIPTION
**Pull request by beatmasterRS**

### CODE REVIEW

**Comment by Nanomani** [comment]
Thanks : ) 
It is better.

IMHO button outside is a bit strange. No ? 



like this what do you think : ?

**Comment by beatmasterRS** [comment]
If you know for sure, that (also in future updates of core/libreelec)

- buttons 1500, 1501 are only used for the connections-tab 
- the content on the right side will never overlap the buttons

this is not a problem ;)

**Comment by beatmasterRS** [comment]
But I am not satisfied with either version :D

**Comment by beatmasterRS** [comment]
screenshot00034

**Comment by Nanomani** [comment]
> If you know for sure, that (also in future updates of core/libreelec)
> 
> * buttons 1500, 1501 are only used for the connections-tab
> * the content on the right side will never overlap the buttons
> 
> this is not a problem ;)

:D 

who can know for sure ?
but i highly doubt that there is a major change to this part for a while.
the official release of Libreelec 10 is not yet available :)
however, if there is a significant change, it will be necessary to modify the code in all case not only for this.

you have time and by then ...
anyway you are the captain on board ;)

**Comment by Nanomani** [comment]
> Something like this would be best:
> 
> screenshot00232
> 
> But this would have to be triggered somehow, for example by a click on a small button, which then calls a yes/no dialog like screenshot.

Yes, why not :)

> Maybe you have an idea? :)

Perhaps :) Currently it will be difficult to find time.
no problem I keep that in mind

> Thanks again for your help. Without your help, especially with the strings and many other things, the skin would not have made it into the official repo! :)

You're welcome :)
thank you for those words. Nice Words are always welcome

**Comment by beatmasterRS** [comment]
I had thougt about it, and your idea with doen right position is the best! :)

**Comment by Nanomani** [comment]
> I had thougt about it, and your idea with doen right position is the best! :)

No problem. Thanks :)

**Comment by beatmasterRS** [comment]
@Nanomani please test the latest changes :)

**Comment by Nanomani** [comment]
> @Nanomani please test the latest changes :)

Tested. all is good for me 
Thanks again :)

**Comment by beatmasterRS** [comment]
Thank you :)

**Pull request merged**
