### PR TITLE
[Background] patch-4

### PR DESCRIPTION
**Pull request by beatmasterRS**

### CODE REVIEW

**Comment by beatmasterRS** [comment]
@Nanomani could you please have a look at  this? The change from commit: https://github.com/beatmasterRS/skin.arctic.zephyr.mod/commit/70b96708a685201e7c85f284a98f72873a575fa2 has broken something. You can see it in the follwing video. the first part has the issue, T-bird_se has mentioned here:

https://forum.kodi.tv/showthread.php?tid=337862&pid=3044728#pid3044728

The second part of the video shows the PR version.

https://youtu.be/-YUc5nzpAko

Currently i have no idea how to fix the errors with "noop" in the log and at the same time got the issue fixed...

Maybe you have an idea :)

**Comment by Nanomani** [comment]
Sorry for that. Please rollback in a first time. Broken something are there worse solutions.
This give me more time to think about it

**Comment by beatmasterRS** [comment]
No problem :) Maybe we found a solution for that. The thing is that I am not comfortable with conditions related to background functions :D

**Comment by beatmasterRS** [comment]
What do you think of a quick & dirty solution, using an empty fake playlist?

**Comment by beatmasterRS** [comment]
What about using an empty playlist to fix this issue?

**Pull request merged**
