### PR TITLE
Add Extra Info view option to Poster Small Wall

### PR DESCRIPTION
**Pull request by garzilla**
happy to answer any questions take direction - not sure if my id numbering is breaking any protocol

the LabelDirector pattern feels like it is abusing the intent of the label - my prior commit had another way to toggle title and director in the extra info top line.

i made it so that if the user has preshow disabled for some reason, it will hide the preshow options in the skin. 
if they have preshow enabled, the preshow play button is default focus in the dialog video info

also - i added a preshowexperience.png for the dialogvideo info

### CODE REVIEW

**Comment by beatmasterRS** [comment]
Thanks for your pr and for your work. There are some changes that have to be made, before the pr can be merged:

1080i/Custom_DialogInfoSettings.xml
- Trailer button is gone
- Cinema button is gone, should be only visible if preshow addon is enabled

1080i/Includes.xml
- Button 49 needs a condition to enable/disable + addon is enabled

1080i/DialogVideoInfo.xml
- not need to check for System.HasAddon(script.preshowexperience) + System.AddonIsEnabled(script.preshowexperience). Only System.AddonIsEnabled(script.preshowexperience) + condition to enable/disable is needed
- may an additional visible check for not empty dbtype/dbid, if that is needed, e.g. if the user uses a video addon. I have not found any documentation about skin integration.
- if using a video addon and dualigvideoinfo opens, no button gets focused.

Language file
- Please add a new language string to en_gb and your favourite language. Kodi weblate adds the missing strings. The reason is, that i am not sure, if it's better to use the old strings, cause cinema experience sounds the best.

1080i/View_517_WallSmall.xml
- Info changes can not be added, cause that doesnt fit to the design, to much space at the right/lift side.

**Comment by garzilla** [comment]
Thank you for the prompt review. Will make changes. Please see follow up questions below the quoted segments. 

> 1080i/View_517_WallSmall.xml
> 
> Info changes can not be added, cause that doesnt fit to the design, to much space at the right/lift side.

Are you saying that it cannot be added at all or that I need to adjust spacing on the right and left borders? I tried to follow same spacing as in the PosterWall with the ExtraInfo enabled.  Maybe a screen shot illustrating spacing needed? 

> Language file
> 
> Please add a new language string to en_gb and your favourite language. Kodi weblate adds the missing strings. The reason is, that i am not sure, if it's better to use the old strings, cause cinema experience sounds the best.
> 
Not familiar with language file - any link? 
Also "Cinema Experience" was the name of the very old add on that is no longer in development. PreShow Experience is the formal add-on name that is in development


> 1080i/DialogVideoInfo.xml
> 
> not need to check for System.HasAddon(script.preshowexperience) + System.AddonIsEnabled(script.preshowexperience). Only System.AddonIsEnabled(script.preshowexperience) + condition to enable/disable is needed

I was wondering about that. i was going to ask if System.AddonIsEnabled eliminated need for System.HasAddon. will fix. 

> may an additional visible check for not empty dbtype/dbid, if that is needed, e.g. if the user uses a video addon. I have not found any documentation about skin integration.

Is there an example in the code?  Skin integration would be the same as it was for Cinema Vision. www.preshowexperience.com is the website. 

> if using a video addon and dualigvideoinfo opens, no button gets focused.
Will check and fix

> 1080i/Custom_DialogInfoSettings.xml
> 
> Trailer button is gone
> Cinema button is gone, should be only visible if preshow addon is enabled

I thought those buttons were for the old Cinema Experience Addon which is no longer in development and not compatible with Kodi 20. That's why I removed.  Does this skin have the ability to play trailers on its own? I will also check with PreShow Experience for skin integration documentation

**Comment by beatmasterRS** [comment]
> Thank you for the prompt review. Will make changes. Please see follow up questions below the quoted segments.
> 
> > 1080i/View_517_WallSmall.xml
> > Info changes can not be added, cause that doesnt fit to the design, to much space at the right/lift side.
> 
> Are you saying that it cannot be added at all or that I need to adjust spacing on the right and left borders? I tried to follow same spacing as in the PosterWall with the ExtraInfo enabled. Maybe a screen shot illustrating spacing needed?
> 

Posters does not fit, cause the info is to wide. The width of the info must be the same everywhere.

> > Language file
> > Please add a new language string to en_gb and your favourite language. Kodi weblate adds the missing strings. The reason is, that i am not sure, if it's better to use the old strings, cause cinema experience sounds the best.
> 
> Not familiar with language file - any link? Also "Cinema Experience" was the name of the very old add on that is no longer in development. PreShow Experience is the formal add-on name that is in development
> 

I know cinema experience as well as cinema vision. The name "Cinema Experience" is used only in one place in the skin, in DialogVideoInfo, and it describes exactly, what the preshow experience addon does.

> > may an additional visible check for not empty dbtype/dbid, if that is needed, e.g. if the user uses a video addon. I have not found any documentation about skin integration.
> 
> Is there an example in the code? Skin integration would be the same as it was for Cinema Vision. [www.preshowexperience.com](http://www.preshowexperience.com) is the website.

I know the website. So there is a documentation for an old addon, that should be used for the new addon? ;)

> > 1080i/Custom_DialogInfoSettings.xml
> > Trailer button is gone
> > Cinema button is gone, should be only visible if preshow addon is enabled
> 
> I thought those buttons were for the old Cinema Experience Addon which is no longer in development and not compatible with Kodi 20. That's why I removed. Does this skin have the ability to play trailers on its own? I will also check with PreShow Experience for skin integration documentation

Sure, the skin has a button to play a trailer (also in window mode) in the DialogVideoInfo.

**Comment by garzilla** [comment]
But it fits and I have checked in every view as well. I didn't change the size.

**Comment by garzilla** [comment]
> Posters does not fit, cause the info is to wide. The width of the info must be the same everywhere.

I do not see where it does not fit. All of the Extra Info views are the same size. 

I apologize for not understanding - maybe the photos help? 






And the poster views of these are not changed





I will remove PreShow code from this PR and create a separate one for it to make it easier to manage

**Comment by garzilla** [comment]
still working through them. 

added the buttons back that i removed. sorry - i misunderstood their use.

**Comment by beatmasterRS** [comment]
No problem :)

Please take a look at the layout changes i've made https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/975/commits/dd85564b1ed98acb2ed3c964fea4d4e7720e261d

There are other changes, that needs to be done with the view 517 and myvideonav. Please split the PR so that there is one PR for the preshow integration and one for the changes to View 517. Thank you.

**Comment by beatmasterRS** [comment]
screenshot01389

screenshot01388

screenshot01387

**Comment by garzilla** [comment]
I appreciate you coding that up - I would NOT have figured out that is what you meant. 
I'll get the rest ASAP.

**Comment by garzilla** [comment]
PR has been split

**Comment by garzilla** [comment]
what else is needed in this one? 
i split the preshow from this PR and made changes. i figure maybe the language files might need updating? not sure

thanks!

**Comment by garzilla** [comment]
sorry for the delay - i will be updating this today/tomorrow

**Pull request closed without merging**
