### PR TITLE
[NowPlaying SkinSettings] changed skin settings, so that is easier to choose the now playing type

### PR DESCRIPTION
**Pull request by beatmasterRS**

### CODE REVIEW

**Comment by PSTrophy** [comment]
What do you mean now playing type? Can you elaborate please :)

**Comment by PSTrophy** [comment]
Nice new toys :) Thanks

**Comment by beatmasterRS** [comment]
It's already implemented in the skin :D 

Skin settings - Extras - Use old Arctic Zephyr underlined ...

Skin settings - colors - gradients settings (one of them, I don't know exactly which one)

**Comment by PSTrophy** [comment]
Just wondering but there's 3 to choose from now one of them called Aus which I think is supposed to be called off maybe?

**Comment by beatmasterRS** [comment]
I knew, i forgot something :D

**Comment by PSTrophy** [comment]
Are you going to implement the other language string changes I mentioned in the spelling and grammar issue or are you waiting for me to find more first ;)

**Pull request merged**
