### PR TITLE
[Home Header] Improvements

### PR DESCRIPTION
**Pull request by Nanomani**
if default ID in home is music   :  

before :  

screenshot00010

screenshot00012

After :

### CODE REVIEW

**Comment by Nanomani** [comment]
This works not only with default ID.
You can change default main menu "Music" to "Albums" or "Artists".

The condition added is bit complicated but I can't do other :/
All is explain here : https://forum.kodi.tv/showthread.php?tid=342211

**Comment by beatmasterRS** [comment]
Sound good! Maybe something like:

string.contains -> plugin.audio

**Comment by Nanomani** [comment]
> Sound good! Maybe something like:
> 
> string.contains -> plugin.audio

Yes. You're right :) 
To be clear, the only thing what I need is what you want :) the code is not a problem :)

**Comment by beatmasterRS** [comment]
I don't use this option, so i don't care as long as it works :D

**Comment by Nanomani** [comment]
> I don't use this option, so i don't care as long as it works :D

Ok I understand. I add the commit tomorrow :)

**Comment by Nanomani** [comment]
if you want it is ready for merge  :)

**Pull request merged**
