### PR TITLE
IMDB rating

### PR DESCRIPTION
**Pull request by mkaflowski**
Added IMDB rating

Zrzut ekranu 2023-01-30 o 22 26 20
Zrzut ekranu 2023-01-30 o 22 24 41
 
Zrzut ekranu 2023-01-30 o 22 48 17

### CODE REVIEW

**Comment by beatmasterRS** [comment]
Thanks for your work! Please remove all unnessesary files

**Comment by mkaflowski** [comment]
> Thanks for your work! Please remove all unnessesary files

Done

**Comment by beatmasterRS** [comment]
Thank you. Looks good so far. Will be merged soon.

**Comment by mkaflowski** [comment]
Thank you.

**Comment by beatmasterRS** [comment]
Please take a look at the conflicts, that needs to be solved. Code has changed with this PR https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/948

**Comment by mkaflowski** [comment]
Fixed

**Pull request merged**
