### PR TITLE
[Feature] add all others icons + cleaning : space end line, tab at beginning of line

### PR DESCRIPTION
**Pull request by Nanomani**

### CODE REVIEW

**Comment by fabricionaweb** [comment]
To clean spaces at final line, I'd suggest us to use [editorconfig](https://editorconfig.org/)

**Comment by Nanomani** [comment]
> To clean spaces at final line, I'd suggest us to use [editorconfig](https://editorconfig.org/) and set `trim_trailing_whitespace`

Actually I use notepad++. But why not use this one. I presume it is better because it does the job automatically ?

**Comment by fabricionaweb** [comment]
Yup! 

editorconfig its just an extension, its available for a lot of editors, it reads the dotfile `.editorconfig` and just apply the rules when you save the file! 



this is good to maintain some consistency

**Comment by Nanomani** [comment]
@beatmasterRS @fabricionaweb 
I always replace some "tab" by "Space" for the consistancy because the whole code is like that 
But it will be great to definitively replace all spaces by tabs. then always keep this use.
It is not so easy because there some space use in <label>

What do you think of that ?

**Pull request merged**
