### PR TITLE
[Home Multi Netflix] option to hide info Widget when focus Home Menu

### PR DESCRIPTION
**Pull request by Nanomani**
option to hide info Widget when focus Home Menu only for Netflix Multi Layout

Modern before - focus home menu

Modern after - focus home menu

Modern - focus widget (like before)

Vertical before - focus home menu

Vertical after - focus home menu

Vertical - focus widget (like before)

Feel free to close ... :D

### CODE REVIEW

**Comment by beatmasterRS** [comment]
Okay, ihave testet. Just to be sure i understand correctly: this option hides the plot, when no widget is focused, right?

**Comment by beatmasterRS** [comment]
- A better description and a fade-animation for the plopping out/in plot would be cool^^

**Comment by Nanomani** [comment]
_"this option hides the plot, when no widget is focused, right? "_

Right :)

_"A better description and a fade-animation for the plopping out/in plot would be cool"_ 

No probleme

For all this things you know more me :D 
 - my english is so bad
 - for other detail my skill is limited

So I try do not put my fingers everywhere and leave you make what is better.
anyway thanks to considering my work :)

**Comment by beatmasterRS** [comment]
My english isnt better. Without deepl.com i had no chance :D 

For the fade animation i have to look at my messy code. :D I think i can trigger the animation with "!Control.HasFocus(300) + !Control.HasFocus(302)".

**Comment by beatmasterRS** [comment]
What about simply adding a line to the "FullScreenInfoSub" include to fade out, if ControlGroup(301) isn't focused? :D

`<animation effect="fade" start="100" end="0" time="150" condition="!ControlGroup(301).HasFocus() + Skin.HasSetting(home.hide.netflix.info)">Conditional</animation>`

**Comment by Nanomani** [comment]
you are totally right :D

**Comment by Nanomani** [comment]
Tested. It is good for me :)

**Review by beatmasterRS — APPROVED** [review]
Looks good :)

**Pull request merged**
