### PR TITLE
[Label ViewType] Improvement and consistancy

### PR DESCRIPTION
**Pull request by Nanomani**
step by step :)

### CODE REVIEW

**Comment by Nanomani** [comment]
It can be usefull to add a new msgctxt for code localization kodi "535" (List) it is the last one ?

**Review by beatmasterRS — CHANGES_REQUESTED** [review]
If you change existing strings, keep in mind that they must also be changed in all other existing language files, where these strings are in use. It would probably be easier if you add new strings for all changes, i think.

What about strings #38004 and #38005?

**Comment by Nanomani** [comment]
Yes I know all of that :)

For #38004 and #38005 it is for my need. I don't like when I do not have the choice.
Added 5 string or 7 make no difference.

Give me some time .I must see how I can find the best method for all language ...
I like to make as little effort as possible :-P

**Comment by Nanomani** [comment]
For consistancy I have added a new msgctxt 38007 "Fanart Flix" for layout 520.
For consistancy I would like to add msgctxt 38008 "List" this is the last word taken in the kodi translation (535) for all viewtype name. Mixing languages ​​for this part is weird for me
but for this last point I need your green light.

otherwise I think I have done what is necessary when is needed for all language.

I can add translations for this languages :
#38004 "Wide"
#38005 "Media info"
#38008 "List"

I don't think it is useful and good to do that for all language.
It is you who decide I am listening to you :-)

**Comment by Nanomani** [comment]
For my part I have finish. I hope I answered all your recommendation.
There is just the question on the out-kodi translation of "list".
This don't must be a pb. I understand if you are not agree. :-)
I have tested with all language in this PR. I have see nothing breaking.
Then the choice to push the button is yours

**Comment by beatmasterRS** [comment]
Thanks, i will have a look soon

**Pull request closed without merging**
