### PR TITLE
[Focus Items] added setting to zoom/glow focused items

### PR DESCRIPTION
**Pull request by beatmasterRS**

### CODE REVIEW

**Comment by beatmasterRS** [comment]
screenshot00462

screenshot00463

screenshot00465

**Comment by beatmasterRS** [comment]
screenshot00473

**Comment by beatmasterRS** [comment]
screenshot00480

**Comment by Nanomani** [comment]
Tested and it is cool. :)
Just IMHO perhaps with mode glow light disable a glow a little bit more strong will be better. 
I know it hard to have the good balance. All of this depend of the screen oled, lcd, HDR, TV settings ... :)
Anyway thanks for this feature.

**Comment by beatmasterRS** [comment]
I will add an "extra light" setting for that :)

**Comment by beatmasterRS** [comment]
Please test the updated version. There will be a setting fpr low, medium and high. Does that fit your needs?

**Comment by Nanomani** [comment]
> Please test the updated version. There will be a setting fpr low, medium and high. Does that fit your needs?

Thanks a lot. It is just perfect. That fit my need and more of people I think. :)

**Pull request merged**
