### PR TITLE
Fade Animation for SubHeaderLabel for TVShows

### PR DESCRIPTION
**Pull request by semool**
I have made a Fade Animation for the TVShows. TVShows Total / unseen with Episodes Total /unseen.
But the Animation Effects killing me ): I need some Assistance please for smooth transision effect.

OK, have it, now its fine :)

### CODE REVIEW

**Comment by beatmasterRS** [comment]
I finally had a bit of time to look at it and test it. Could you make it so that when I switch from "Movies" to "Series", the animation first starts when is will switch to episodes information? :) And the animation speed should be faster, like the animation in DialogVideoInfo, when the labelinfo/pathinfo fades out/in:

`<effect type="fade" end="100" start="0" time="400" delay="2300"/>`
`<effect type="fade" end="0" start="100" time="400" delay="2000"/>`

If you need help with animation, please let me know 

thanks :)

**Comment by semool** [comment]
OK Faster Transition is added. I dont think its possible to start the Animation from the beginning by switching Menupoints?
Show the Plot Boxes for Movies, they already keep scrolling when you switch away and come back.

**Comment by beatmasterRS** [comment]
It's a shame. I tried it now and it actually works fine, except when you call up Tv Shows and then switch back to the main menu, some animations start too fast.

**Comment by semool** [comment]
No they start not to fast, they running constantly. When you go back 1 sec before the switch, its switches 1 sec later. It looks wrong sometimes but it is the functionality how an animation works in a loop.

**Comment by beatmasterRS** [comment]
I'm sorry, i forgot to say that i have tried to find a solution myself:

```
               <control type="label">
                    <visible>$EXP[IsSubHeaderLabel2]</visible> 
                    <centertop>58</centertop>
                    <font>Flag</font>
                    <include condition="Skin.HasSetting(furniture.logo) + !Window.IsVisible(home) + !Window.IsVisible(settings) + !Window.IsVisible(skinsettings) + !Window.IsVisible(SettingsCategory.xml) + !Window.IsVisible(tvchannels) + !Window.IsVisible(tvrecordings) + !Window.IsVisible(tvguide) + !Window.IsVisible(tvsearch) + !Window.IsVisible(tvtimers)">HeaderLabelWidthLogo</include>
                    <width>auto</width>
                    <textcolor>Dark2</textcolor>
                    <label>$VAR[SubHeaderLabel2]</label>
                    <animation type="Conditional" condition="System.IdleTime(3)">
                        <effect type="fade" start="100" end="0" time="400" />
                    </animation>
                </control>
                <control type="label">
                    <centertop>58</centertop>
                    <font>Flag</font>
                    <include condition="Skin.HasSetting(furniture.logo) + !Window.IsVisible(home) + !Window.IsVisible(settings) + !Window.IsVisible(skinsettings) + !Window.IsVisible(SettingsCategory.xml) + !Window.IsVisible(tvchannels) + !Window.IsVisible(tvrecordings) + !Window.IsVisible(tvguide) + !Window.IsVisible(tvsearch) + !Window.IsVisible(tvtimers)">HeaderLabelWidthLogo</include>
                    <width>auto</width>
                    <visible>$EXP[IsSubHeaderLabel2]</visible>
                    <textcolor>Dark2</textcolor>
                    <label>$VAR[SubHeaderLabel]</label>                    
                    <animation type="Conditional" condition="$EXP[IsSubHeaderLabel2]" loop="true" reversible="false">
                        <effect type="fade" start="0" end="100" time="400" delay="3400" />                        
                        <effect type="fade" start="100" end="0" time="400" delay="6800" />
                    </animation>                    
                </control>                
                <control type="label">
                    <centertop>58</centertop>
                    <font>Flag</font>
                    <include condition="Skin.HasSetting(furniture.logo) + !Window.IsVisible(home) + !Window.IsVisible(settings) + !Window.IsVisible(skinsettings) + !Window.IsVisible(SettingsCategory.xml) + !Window.IsVisible(tvchannels) + !Window.IsVisible(tvrecordings) + !Window.IsVisible(tvguide) + !Window.IsVisible(tvsearch) + !Window.IsVisible(tvtimers)">HeaderLabelWidthLogo</include>
                    <width>auto</width>
                    <visible>$EXP[IsSubHeaderLabel2] + System.IdleTime(3) + Window.IsVisible(home)  + Window.IsVisible(home) + !Window.IsVisible(MyVideoNav.xml)</visible>
                    <textcolor>Dark2</textcolor>
                    <label>$VAR[SubHeaderLabel2]</label>                    
                    <animation type="Conditional" condition="$EXP[IsSubHeaderLabel2] + System.IdleTime(3)" loop="true" reversible="false">
                        <effect type="fade" start="0" end="100" time="400" delay="4200" />                        
                        <effect type="fade" start="100" end="0" time="400" delay="6800" />
                    </animation>                    
                </control>
```

If i reload the skin and focus "tvshows" first there is no fading effect. after 3 seconds the first label fades out and the second fades in. From there it's looping. These were my attempts. It's a pity that you can't change the fade times with a fadelabel control....

**Pull request closed without merging**
