### PR TITLE
[Show now playing info] improvement "paused" information

### PR DESCRIPTION
**Pull request by Nanomani**
when playing is paused with "Show now playing info"

### CODE REVIEW

**Comment by Nanomani** [comment]
if you are agree with this so the same must do for music visualisation about "discart" when playing is paused ...

**Comment by Nanomani** [comment]
@beatmasterRS , like this it can be merge :)

other part will be added later if possible ...

**Comment by beatmasterRS** [comment]
Cant be merged, cause the label you've mentioned in your screenshot is the widget-label. Means that it describes the widget e.g. "now playing widget", not the player status itself. In this case, the player-status is shown with an icon next to the duration :)

**Comment by Nanomani** [comment]
@beatmasterRS 
> the player-status is shown with an icon next to the duration :)

I know that but it is too much discreet for my eyes for real usage 
Then it is strange for me to see ""Now playing..." for media paused o_O

I have understand this is a description. And for consistency it is not possible to touch that :)

1 - this part is a bit differente of the widgets (1, 2 ,3 ... 6)
2 - there is a confuse for who don't know ...

I don't know if you see what I mean .

**Comment by beatmasterRS** [comment]
We could find a better name, e.g. "Now In Player" or something...

**Comment by Nanomani** [comment]
"Now In Player" is better :)

I sincerely apologize for being stubborn or sometimes blocked on tiny things. : /
I must reflect on my side to better identify a media paused. And make you an acceptable proposition :)

**Comment by beatmasterRS** [comment]
All good, we are all human and everyone thinks a bit differently, I also :D

**Comment by Nanomani** [comment]
> @beatmasterRS
> 
> > the player-status is shown with an icon next to the duration :)
> 
> I know that but it is too much discreet for my eyes for real usage
> Then it is strange for me to see ""Now playing..." for media paused o_O
> 
> I have understand this is a description. And for consistency it is not possible to touch that :)
> 
> 1 - this part is a bit differente of the widgets (1, 2 ,3 ... 6)
> 2 - there is a confuse for who don't know ...
> 
> I don't know if you see what I mean .

I m not alone :)
sorry I couldn't resist :D
https://github.com/beatmasterRS/skin.arctic.zephyr.mod/issues/175

**Pull request closed without merging**
