### PR TITLE
[SkinSettings] improvements rework

### PR DESCRIPTION
**Pull request by Nanomani**
Sorry I have not enought right to push my PR in yours. So ...

### CODE REVIEW

**Comment by beatmasterRS** [comment]
Bad news: There is a problem, i am not able to fix:

image

- No underlines are possible
- if i use <textoffsetx>70</textoffsetx>, the value is used also on the right side...

**Comment by beatmasterRS** [comment]
Bad news: There is a problem, i am not able to fix:

screenshot00048


No underlines are possible
if i use 70, the value is used also on the right side...

**Comment by beatmasterRS** [comment]
Hmm so either insist on consistency, or change only in skin settings... Or maybe you found a way, but currently i have no idea...

**Comment by Nanomani** [comment]
the problem is about `msgid "     "` I presume.

If yes there is an other solution :)

**Comment by beatmasterRS** [comment]
Please have a look at settings category.xml

**Comment by Nanomani** [comment]
I got it.
I will check all that ...

**Comment by beatmasterRS** [comment]
Nice!

**Comment by Nanomani** [comment]
I tried to do the same for the Kodi settings but without success :/
I can't add the line under the titles ...

**Comment by beatmasterRS** [comment]
The Same issue hast bosered me a lot ... I ll be back in two hours, when I'm back from work :D

**Comment by beatmasterRS** [comment]
Theoretically, the items in SettingsCategory.xml should also be moved a little to the right, right?

screenshot00051

**Comment by Nanomani** [comment]
> Theoretically, the items in SettingsCategory.xml should also be moved a little to the right, right?

right :)

**Comment by beatmasterRS** [comment]
Could you please try to do this? I was not successful

**Comment by Nanomani** [comment]
I can't do better than this :

**Comment by beatmasterRS** [comment]
I have not done more than that :/ Or we use this only in the SkinSettings? I have no idea. Too bad there is no solution for this yet. I have also already looked in other skins, but so really I have found nothing that could help...

**Comment by Nanomani** [comment]
> we use this only in the SkinSettings? 

Yes, if you are agree :)

> I have no idea. Too bad there is no solution for this yet. 

Totally agree

>I have also already looked in other skins, but so really I have found nothing that could help...

I had the same approach without success

**Comment by Nanomani** [comment]
@beatmasterRS, I have post a thread here : 
https://forum.kodi.tv/showthread.php?tid=363306

wait and see if there is positive feedback ...

**Comment by beatmasterRS** [comment]
I hope so :)

**Comment by Nanomani** [comment]
Yes and no :D 
we can never have anything other than that with line : 
Please try with Estuary Skin "Kodi Settings" to understand"
(The first line is fixe)



I need to check again if a clean right alignment is possible :)
What do you think about line ?

**Comment by Nanomani** [comment]
clean right alignment is possible.
Probably the best I can do with "Kodi settings" GUI :

**Comment by beatmasterRS** [comment]
Please can you push some code, so I can test? :)

**Comment by Nanomani** [comment]
> Please can you push some code, so I can test? :)

Some minor adjustment will be needed here and here.
But I thinks you can test :)

**Comment by beatmasterRS** [comment]
Looks good, i have made some tests:

**Comment by Nanomani** [comment]
> Looks good, i have made some tests:

If you want that the consistency is more close. It is possible to place too the line in "skin settings" above the title  ?

**Comment by beatmasterRS** [comment]
screenshot00053
screenshot00054
screenshot00055
screenshot00056
screenshot00057

**Comment by beatmasterRS** [comment]
But there is an issue... :I 

https://youtu.be/Y-cuF6phmhs

**Comment by beatmasterRS** [comment]
https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/343

**Comment by beatmasterRS** [comment]
If we disable gradients for settingscategory.xml, all should be working fine, Maybe you have an idea how to fix this...? :)

**Comment by Nanomani** [comment]
> But there is an issue... :I
> 
> https://youtu.be/Y-cuF6phmhs

during my tests I had this issue at one time
But I have been following your video carefully. I failed to reproduce this issue again
If you test only my latest code without change line in "Skin Settings" can you reproduce that ?

**Comment by Nanomani** [comment]
> If we disable gradients for settingscategory.xml, all should be working fine, Maybe you have an idea how to fix this...? :)

I can check :)

**Comment by beatmasterRS** [comment]
For me the issue still exsists, cause the gradients overlay always slide 70 px per item. The item with line png is only 1 px in height, so that causes that, the gradients overlay slides to much...

**Comment by beatmasterRS** [comment]
https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/344

For more consistency between skin settings and settingscategory.xml

**Comment by Nanomani** [comment]
o_O before #343 or #344  I can't reproduce

https://github.com/Nanomani/skin.arctic.zephyr.mod/archive/refs/heads/SkinSettings_improvements_rework.zip

with #343 or #344 I can :D

**Comment by beatmasterRS** [comment]
Maybe an other option is, if we only underline the right header/overline the first item, if nothing else is possible due to gradients overlay issues...

**Comment by beatmasterRS** [comment]
Like so:

screenshot00061
screenshot00062

**Comment by beatmasterRS** [comment]
Just a thought:

screenshot00063
screenshot00064

**Comment by beatmasterRS** [comment]
I personaly would prefere option 2, because:

- no issues with navigation
- no gradients issue
- absolutely consistent

**Comment by beatmasterRS** [comment]
I am unfortunately very undecided about what looks good and what does not... :D

**Comment by Nanomani** [comment]
> I personaly would prefere option 2, because:
> 
> * no issues with navigation
> * no gradients issue
> * absolutely consistent

Ok go for 2 :D 

> Its a shame, that we can use things in settingscategory like in skinsettings :(

Day after day your skin is better and better. Tomorrow is another day :)

**Comment by Nanomani** [comment]
> I am unfortunately very undecided about what looks good and what does not... :D

the 2 is a perfect compromise (better than before in any case and remains light)
"absolutely coherent" pleases me a lot :D 
then it will more easy to do the same for Libreelec and Coreleec :)

**Comment by beatmasterRS** [comment]
Okay, i have updated the PR, so please test the last version :) I hope, i havent broke any things...

**Comment by Nanomani** [comment]
Look very good. Thanks :) 
No issue for me

In option 2 there a line in left panel. In this update line don't exist. It is not a missing I guess ? No problem for me :)

Consistent is so perfect. A little time is needed to be sure where we are. :D
Perahps a logo like for Libreelec or Coreelec can be cool. I dont know ?

screenshot00003

**Comment by beatmasterRS** [comment]
I had removed the line on the left, cause i thin k its to much. For now i am finished with improvements :)

>>Perahps a logo like for Libreelec or Coreelec can be cool. I dont know ?

Do you mean in libre/coreelec Dialog?



As always a great job, my friend! :)

**Comment by beatmasterRS** [comment]
In coreelec Dialog there is also a logo like on the screen you have posted from libreeelc:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/23d7f0a4c0959d2a10e60e91d2ad0c35dffbaa45/1080i/service-CoreELEC-Settings-mainWindow.xml#L81-L89#

Do you mean this?

**Comment by Nanomani** [comment]
> In coreelec Dialog there is also a logo like on the screen you have posted from libreeelc:
> 
> https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/23d7f0a4c0959d2a10e60e91d2ad0c35dffbaa45/1080i/service-CoreELEC-Settings-mainWindow.xml#L81-L89#
> 
> Do you mean this?

Yes :)

**Comment by beatmasterRS** [comment]
Was this not there before with libreecel window or for what you have asked? :D

**Comment by Nanomani** [comment]
:)

**Comment by beatmasterRS** [comment]
The AZR Logo maybe, im not sure. The Kodi logo not. I have to think about it :)

Can I merge this PR?

**Comment by Nanomani** [comment]
Sure :) 👍

**Comment by beatmasterRS** [comment]
Maybe you could open a new PR, so we can test the things with logos, etc?

**Pull request merged**
