### PR TITLE
[DialogSelect "Set My Rating"] fit user color star

### PR DESCRIPTION
**Pull request by Nanomani**
little improvement cosmetic that make sens for me. 
I leave you the decision :)

before : 

after :

### CODE REVIEW

**Comment by beatmasterRS** [comment]
Is this the thing you brought up last forum? :) I think the stars should keep in the highlight color, thanks :)

**Comment by Nanomani** [comment]
> Is this the thing you brought up last forum? :) I think the stars should keep in the highlight color, thanks :)

Yes in part. 
This means that to be completely correct you have to apply this also in the star media flag when "User override rating" is enable.
IMHO what is not complicated to do for me...

I understand your answer that make sense . 
I had anticipated it. It was just in case... :) 
No problem :)

**Comment by beatmasterRS** [comment]
Where is your AZR branch??? :s

**Comment by Nanomani** [comment]
> Where is your AZR branch??? :s

It is on my local github.
I didn't want any confusion with forum users. 
And even if I progressed I do not believe that my code is relevant especially for you :)

**Comment by beatmasterRS** [comment]
Too bad, because there were a few things that I found interesting and were good ideas... Anyway happy easter :)

**Comment by Nanomani** [comment]
> Too bad, because there were a few things that I found interesting and were good ideas... 

O_o which idea?

> Anyway happy easter :)

You too my friend ;)

**Comment by Nanomani** [comment]
If I can help please ask me :)

**Comment by beatmasterRS** [comment]
E.g. the wikipedia code ;)

**Comment by Nanomani** [comment]
Your wikipedia code works well. 
I have just adapted 1 or 2 tiny things for my need.
Eg : Wiki for the cast

**Comment by Nanomani** [comment]
don't be afraid i'll leave you alone afterwards ;)

As far as my code is concerned, reverse engineering is taking me more and more time without breaking my AZR nexus mod to add one of your new interesting features.

eg : [NowPlaying] added option to auto show nowplaying 

It is cool feature. But like you said manage all condition make me crazy :D 
the next evolutions I have in mind will definitely make following your code very difficult or impossible...

**Comment by beatmasterRS** [comment]
>Your wikipedia code works well.
I have just adapted 1 or 2 tiny things for my need.

Yes, but the code i started with, was from you azr branch :) cause for me a few month ago i did not get it to work :D Then a few weeks ago, i saw the commits in your branch :)

**Comment by beatmasterRS** [comment]
> It is cool feature. But like you said manage all condition make me crazy :D the next evolutions I have in mind will definitely make following your code very difficult or impossible...

i am excited, what ideas do you have in mind :)

**Comment by beatmasterRS** [comment]
@Nanomani I have a question. Isn't it better to hide the whole menu when the option "hide, when not focused/used" is enabled? The option label actually describes exactly that :) 
A user on the kodinerds forum brought this to my attention. Or is it better to add an option like "Hide menu items only"?

screenshot01391

screenshot01390

**Comment by Nanomani** [comment]
> better to hide the whole menu when the option "hide, when not focused/used" is enabled?

I agrea with that. It is better to me. 
This works like that on my side by default.

I have added "Hide home menu with NowPlaying" only if a user prefer to see always the menu without "NowPlaying".



that mean 

`[!Skin.HasSetting(homemenu.slide) | [$EXP[HomeIsVerticalMultiWidgets] + Skin.HasSetting(homemenu.vertical.noslide)]]`

Then the menu slide only with "NowPlaying". 

IMHO it less confuse for the user like that 
But it is a next step for you if this it is asked...

**Comment by Nanomani** [comment]
But you always better idea than me :D

**Comment by beatmasterRS** [comment]
Ich think it's a good idea! I also had seen that in ah2 :) i take a closer look later today, when I have more time :)

**Comment by Nanomani** [comment]
> Is there someting to test? :)

About presets ?
Not at all :)

**Pull request closed without merging**
