### PR TITLE
[Background Code] changed control type from multiimage to image

### PR DESCRIPTION
**Pull request by beatmasterRS**
- changed control type to image,  as there is no reason to use multiimage. 
- better control by constant "HomeTimePerImage" about time per image, when extrafanart is used.

### CODE REVIEW

**Comment by semool** [comment]
Hmm with this change i have absolutly no Backgrounds at all. Reverted to the old Includes.xml and all is fine again.

**Comment by PSTrophy** [comment]
Same here. No backgrounds or fanart do you have to setup the images again?

**Comment by beatmasterRS** [comment]
Can you please test, if its better now with the latest master?

**Comment by PSTrophy** [comment]
All fixed for me. Thanks

**Comment by semool** [comment]
Yes, here is also fine, THX

**Pull request merged**
