### PR TITLE
[Colorbox Blur] added option to use colorbox script for blur

### PR DESCRIPTION
**Pull request by beatmasterRS**
…elper for blur

### CODE REVIEW

**Comment by beatmasterRS** [comment]
@Nanomani @fabricionaweb @semool  maybe you would like to test this PR. 

With this PR, the user can enable colorbox for blur. In my tests the colorbox script is much faster then embuary for blurring images. Of course in embuary you can set the script service intervall to 0.2 or 0.1 to get faster image changing. But colorbox is much faster out of the box.

I think, if colorbox script will be added to the official kodi repo, i will add this as a dependency.

But for now, I'm not sure how to implement this, also to get a good user experience. 
My goal would be of course if the blur function could be only handled by the colorbox script, when colorbox is available through the official repo.

What do you think about this?

**Comment by Nanomani** [comment]
Forum : https://forum.kodi.tv/showthread.php?tid=318626
Zip : https://github.com/BADMS/script.colorbox/archive/refs/heads/master.zip
Git : https://github.com/BADMS/script.colorbox

colorbox is very fast. It is great improvement. :)

> But for now, I'm not sure how to implement this

colorbox is not yet in the official repo
So like that is pretty good to prepare people and transition when is possible

I have not understand the setting "Blend". I have not see real difference on the picture :/

**Comment by beatmasterRS** [comment]
I think in Kodi Leia "blend" was something like transparency, but i did not know this anymore :D As you can see in the kodi forum, **badaas** said, that he wants to push a matrix version of lightbox or colorbox :) Thats absolutely great. 

And i think, the blur quality is even better with colorbox :)

**Comment by beatmasterRS** [comment]
I would like to move the "Use colorbox script" setting to the blur-settings section, but changing this option needs a skin-reload, cause the releated blur-settings gets included per condition...

I hope, a matrix script will be official available soon, then this option will be removed. :)

**Comment by Nanomani** [comment]
> I think in Kodi Leia "blend" was something like transparency, but i did not know this anymore :D As you can see in the kodi forum, **badaas** said, that he wants to push a matrix version of lightbox or colorbox :) Thats absolutely great.
> 
> And i think, the blur quality is even better with colorbox :)

Yes, all is better. You can push this PR :)

**Pull request merged**
