### PR TITLE
Bugfix ClearLogo: ClearLogoHomeImageContainer

### PR DESCRIPTION
**Pull request by semool**

### CODE REVIEW

**Review by beatmasterRS — COMMENTED** [review]
Please provide more infos about your PR. Screenshots, where i can see the difference and reproduce the behaviour, would be nice.

**Comment by semool** [comment]
Before:
before1
before2
After:
after1
after2

**Comment by beatmasterRS** [comment]
I could not reproduce this behavior yet. For me it looks like:

Before
screenshot00549

After
screenshot00550

What options do you have enabled for the homemenu?

**Comment by semool** [comment]
Style: Modern Multi Widgets
Home Menu Bar: Standard
transparent Home Menu: True
Display Symbole: True
Show Header (HomeMenu): True
Clearart: True

**Comment by beatmasterRS** [comment]
Unfortunately, I still cannot reproduce this behavior. Can anyone help?

**Comment by Nanomani** [comment]
I m bit curious so I have make a test.
I can't reproduce this too. It is just FYI. :)

**Pull request closed without merging**
