### PR TITLE
[DialogVideoInfo] setting "Prefer IMDb instead of financial" added

### PR DESCRIPTION
**Pull request by Nanomani**
See here : https://github.com/beatmasterRS/skin.arctic.zephyr.mod/issues/590

**With "Prefer IMDb instead of financial" enable :**  

movies 

TV Shows 

.

**With "Prefer IMDb instead of financial" disable :**  

movies :  

TV Shows :

### CODE REVIEW

**Comment by beatmasterRS** [comment]
I close this issue. If you have another solution, like mentioned here: 

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/592#issuecomment-949666270

please open an other PR, thank you.

**Comment by Nanomani** [comment]
no problem :)

FYI I understood your explanations
I have try your code but sorry without total success.

It's frustrating not to be successful. But I think I will spend hours there when it will be faster for you. 
I am stubborn but you have to know abandoned sometimes.

nothing urgent here I will wait :)

**Comment by beatmasterRS** [comment]
You can open another PR, so i can see whats wrong with the code and can help :)

**Comment by beatmasterRS** [comment]
A PR for that is made and all tests going well:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/614

**Pull request closed without merging**
