### PR TITLE
[MENU] Underlined items vertical multi widgets homemenu

### PR DESCRIPTION
**Pull request by Nanomani**
all the conditions must be good
works with icon enable
Underlined-items works with sub menu
Tested with "vertical multi ..." and "horizontal multi..." layout

2 remaining problem :

1 - Label of the main menu uses the label of the item focused
2 - The design with label "main menu + icon" must be improved for consistency

Point 1

Point 2 - line (4867 to 4894) in Includes_Home.xml

### CODE REVIEW

**Review by beatmasterRS — COMMENTED** [review]
For problem 1. You can use "Container(300)", e.g.: 

`$INFO[Container(300).ListItem.Label]` 

to fix this, i think :)

**Comment by Nanomani** [comment]
Yes. Point 1 is fixed. thanks :) 

for "2 - The design with label "main menu + icon" must be improved for consistency". 

My skill is limited. I will not know how to do that...

**Comment by beatmasterRS** [comment]
Just have found a quick (& dirty?) way to underline to underline the icons too. Lines 4867-4893

```
<control type="group">
    <control type="image">
        <right>10</right>
        <width>80</width>
        <top>-5</top>
        <height>80</height>
        <texture colordiffuse="Dark1">$INFO[ListItem.Icon]</texture>
    </control>
    <control type="grouplist">
        <orientation>horizontal</orientation>
        <right>20</right>
        <left>0</left>
        <align>right</align>
        <aligny>center</aligny>
        <height>100%</height>
        <control type="button">
            <textcolor>Dark1</textcolor>
            <font>Home</font>
            <textoffsetx>0</textoffsetx>
            <width>auto</width>
            <texturenofocus border="8" colordiffuse="$VAR[ColorHighlight]">common/underline2.png</texturenofocus>
            <label>$INFO[Container(300).ListItem.Label]        </label>
        </control>
    </control>
    <visible>!Skin.HasSetting(homemenu.only.icons) + Skin.HasSetting(home.showicons) + Skin.HasSetting(homemenu.items.underlined)</visible>
    <animation effect="fade" start="100" end="50" delay="0" time="150" condition="!Control.HasFocus(300) + !Control.HasFocus(302)">Conditional</animation>
</control>
```

Replace lines with this one and the icons are underlined too :)

Now we need to bring all togehter with conditions :)

**Comment by beatmasterRS** [comment]
I will take a look at it, when im back from work :) So is this all completed? :)

**Comment by Nanomani** [comment]
This make the job. It is fine for me :)

it is stay a tiny bug : 
"Home menu" label disapear if you open the power menu ...

**Comment by Nanomani** [comment]
me too I can't see that now only tonight :)

**Comment by Nanomani** [comment]
if you want to be perfect, underlined item is a bit too long at right :

**Comment by beatmasterRS** [comment]
I have done my best with the latest commit. Please test and let me know, what you think ^^ I think its a little bit better, but not perfect..

**Comment by beatmasterRS** [comment]
Here you can see the changes. the first part is the new one :)

https://youtu.be/0Navct2AAGc

**Comment by Nanomani** [comment]
It is better 👍

**Comment by beatmasterRS** [comment]
Thanks for your feedback, then I will merge this PR :)

**Pull request merged**
