### PR TITLE
[Fix] fallback image OSD music or Slideshow

### PR DESCRIPTION
**Pull request by Nanomani**
see : https://github.com/beatmasterRS/skin.arctic.zephyr.mod/issues/362

### CODE REVIEW

**Review by beatmasterRS — CHANGES_REQUESTED** [review]
Following situation:

>- fallback image is set/enabled
>- show fanart is diabled
>- show AS is disabled

i got a blackscreen, cause 

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/12bc65ec768299e34ea7fdbc02c167efb6a18ee7/1080i/MusicVisualisation.xml#L18

the fallback fanart will only be shown if Window(Visualisation).Property(ArtistSlideshow.Image) is empty

**Review by beatmasterRS — APPROVED** [review]

**Comment by beatmasterRS** [comment]
A condition is also needed for following situation:

>- fallback image is set/enabled
>- show fanart is enabled an not empty
>- show AS is disabled

In this situation the fallback image and the fanart image are shown, so i think there should also be the issue, right?

**Comment by Nanomani** [comment]
replace with this must work :) 

`!String.IsEmpty(Skin.String(fanart.fallback.music))  + [String.IsEmpty(Window(Visualisation).Property(ArtistSlideshow.Image)) | !System.HasAddon(script.artistslideshow) | Skin.HasSetting(ArtistSlideShow.Disabled)]</visible> `

**Comment by beatmasterRS** [comment]
i forgot to push my changes :D

**Review by beatmasterRS — APPROVED** [review]

**Comment by Nanomani** [comment]
I make some test ...

**Comment by beatmasterRS** [comment]
Oh my god, Github is going to drive me crazy...

**Comment by Nanomani** [comment]
actually : 

fallback + fanart enable + AS3 disable => fallback 
fallback + fanart enable + AS3 enable => Fanart if found (local / AS3) 
fallback + fanart enable + AS3 enable  => fallback if any fanart found (local / AS3) 
fallback empty + fanart disable + AS3 disable => black screen

**Comment by Nanomani** [comment]
1 and 7 are not good

**Comment by beatmasterRS** [comment]
I can not confirm 1 and 7. This only occurs, if Player.Art(fanart) is empty, which is possible imho.

**Comment by Nanomani** [comment]
> I can not confirm 1 and 7. This only occurs, if Player.Art(fanart) is empty, which is possible imho.

yes  but for : 
1 it is always fallback I have tested all case). which one must be priority ?
7 always black screeen :/

**Comment by beatmasterRS** [comment]
for 1.: fallback is only shown, if "AS is disabled OR empty" and "fanart is disabled OR empty" right?

You can test if $INFO[Player.Art(fanart)] is filled, by just do an output through a label control.

**Comment by Nanomani** [comment]
> for 1.: fallback is only shown, if "AS is disabled OR empty" and "fanart is disabled OR empty" right?

right :) 
that's what I understood

> You can test if $INFO[Player.Art(fanart)] is filled, by just do an output through a label control.

with the debug mode I presume  :)

**Comment by Nanomani** [comment]
the result is good "path/fanart.jpg"

 '<visible>Skin.HasSetting(musicvis.fanartfallback)</visible>` is normal ?

in 

```
        <control type="image">
            <aspectratio>scale</aspectratio>
            <include>Dimensions_Fullscreen</include>
            <texture background="true">$INFO[Player.Art(fanart)]</texture>
            <visible>!System.HasAddon(script.artistslideshow) | Skin.HasSetting(ArtistSlideShow.Disabled)</visible>
            <visible>Skin.HasSetting(musicvis.fanartfallback)</visible>
            <animation effect="fade" start="100" end="65" time="0" condition="Skin.HasSetting(OSDVisualisation.ShowFanart)">Conditional</animation>
            <animation effect="zoom" start="110" end="130" center="auto" time="10000" tween="sine" easing="inout" pulse="true" condition="Skin.HasSetting(ArtistSlideshow.Animate)">Conditional</animation>
            <animation effect="slide" start="-30,-30" end="30,30" time="6000" tween="sine" easing="inout" pulse="true" condition="Skin.HasSetting(ArtistSlideshow.Animate)">Conditional</animation>
        </control>
```

**Comment by Nanomani** [comment]
Good night :D

**Comment by Nanomani** [comment]
I got it. My bad in part :D 

I never use settings for enable/disable Slideshow 

`Skin.HasSetting(ArtistSlideShow.Disabled)`

But I disable/enable add-on  from add-ons manager :D 
Perhaps a control on this can be an improvement ?

`System.AddonIsEnabled(script.artistslideshow)`

arf ! knowing this I will redo the tests ...

**Comment by Nanomani** [comment]
Memo : 

```
music fallback ? =>				String.IsEmpty(Skin.String(fanart.fallback.music))

music fanart enable ? => 		Skin.HasSetting(musicvis.fanartfallback)

music AS3 disable =>			Skin.HasSetting(ArtistSlideShow.Disabled)

Addons AS3 enable ? =>  		System.AddonIsEnabled(script.artistslideshow)

Addons AS3 installed ? => 		System.HasAddon(script.artistslideshow)
```

**Comment by beatmasterRS** [comment]
Try your best :D But for now, i can merge this PR?

**Comment by Nanomani** [comment]
Yep :)

**Comment by Nanomani** [comment]
dumb question ?

`<visible>!String.IsEmpty(Skin.String(fanart.fallback.music)) + String.IsEmpty(Window(Visualisation).Property(ArtistSlideshow.Image))</visible>`

it is the same with this ?

```
<visible>!String.IsEmpty(Skin.String(fanart.fallback.music))</visible>
<visible>String.IsEmpty(Window(Visualisation).Property(ArtistSlideshow.Image))</visible>
```

**Comment by beatmasterRS** [comment]
Mostly this is the same, but I don't know for sure...

**Comment by Nanomani** [comment]
> Mostly this is the same, but I don't know for sure

with which one please ? :)

**Pull request merged**
