### PR TITLE
[Music Visualisation] improvement

### PR DESCRIPTION
**Pull request by Nanomani**

### CODE REVIEW

**Comment by Nanomani** [comment]
I think I have tested everything that is possible :D

**Comment by beatmasterRS** [comment]
Looks good, but a note: 

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/283fe5b8361dc8698a75fd0d37ee996011c16258/1080i/MusicVisualisation.xml#L27

Why using !System.HasAddon(script.artistslideshow) AND  !System.AddonIsEnabled(script.artistslideshow) ? "!System.HasAddon(script.artistslideshow)" is obsolete, isnt it? :)

**Comment by Nanomani** [comment]
Because I m tired :)
I check this ...

**Comment by Nanomani** [comment]
Sorry not sure to understand
1 - !System.HasAddon(script.artistslideshow) => check if missing on kodi
2 - !System.AddonIsEnabled(script.artistslideshow) => check if disable 

1 can be true and not 2

https://kodi.wiki/view/List_of_boolean_conditions

**Comment by beatmasterRS** [comment]
With kodi matrix the "System.AddonIsEnabled" infobool was added. There where some "System.HasAddon" infobools in skin code. I have not made any changes to many of them because they are either not necessary or do not work. E.g. in the skin settings. There it is checked if the addon is installed and if it is enabled. Therefore you need both infobools there

But in this situation, we need not to proof, if System.HasAddon OR System.AddonIsEnabled, cause:

System.AddonIsEnabled is false, if the addon is not installed. You know what i mean? :D

**Comment by beatmasterRS** [comment]
We only need to check if its enabled/disabled, scince it can only be enabled, if its installed.

**Comment by Nanomani** [comment]
> We only need to check if its enabled/disabled, scince it can only be enabled, if its installed.

Okay 👍
I must go to work.... (win money :D)
I make change later

**Comment by Nanomani** [comment]
not the first time :D 
https://github.com/beatmasterRS/skin.arctic.zephyr.mod/commit/bab58c5191f35fb1160c53767acbd39d286f0efa

Anyway this must be good this time :)

**Comment by beatmasterRS** [comment]
These PR improved the code a bit.

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/366

**Comment by beatmasterRS** [comment]
Is it ready for merge? :)

**Comment by Nanomani** [comment]
Yes :)

**Pull request merged**
