### PR TITLE
[Fix]  ERROR "GetDirectory - Error getting noop" in LOG

### PR DESCRIPTION
**Pull request by Nanomani**
After comment the line 90 in Includes_Defs.xml

this error that appear often in the LOG Kodi  :

`ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting noop`

Disapear and I see nothing break in skin AZR ...

### CODE REVIEW

**Comment by Nanomani** [comment]
more investigation is needed ...
there are again this error much less.But it shouldn't appear at all

**Comment by Nanomani** [comment]
@beatmasterRS I have a stupid question. 
Do you have a synonym for noop ? This word appears many times in code.
it's not clear to me :S

**Comment by beatmasterRS** [comment]
I have used this, cause it was in the skin on several lines. Also other skins are using that. Maybe a empty value would be a solution, I have no idea:

<value condition="abc" />

Untested just a try :D

**Comment by Nanomani** [comment]
@beatmasterRS 
you are right. empty value is better. No more `"ERROR "GetDirectory... `in log
do not panic. I deleted it in 3 lines only :D

**Comment by beatmasterRS** [comment]
Thank you very much :)

**Pull request merged**
