### PR TITLE
[Views] Added extended gamemode views

### PR DESCRIPTION
**Pull request by chrisism**
Added extra views support for different type of game modes (retroplayer and addons).
Includes support for more game metadata.

### CODE REVIEW

**Comment by chrisism** [comment]
How to add the texts now? Cannot merge if I add it to the language files.
```
msgctxt "#31690"
msgid "Player"
msgstr ""

msgctxt "#31691"
msgid "Players"
msgstr ""
```

**Comment by beatmasterRS** [comment]
> How to add the texts now? Cannot merge if I add it to the language files.
> 
> ```
> msgctxt "#31690"
> msgid "Player"
> msgstr ""
> 
> msgctxt "#31691"
> msgid "Players"
> msgstr ""
> ```

What do you mean with that exactly? Just add the strings to your pr.

**Comment by chrisism** [comment]
Here it is, but it says it has conflicts.

**Comment by beatmasterRS** [comment]
Should be fine now.

**Pull request merged**
