### PR TITLE
Widgetsortdirection

### PR DESCRIPTION
**Pull request by semool**
This isnt working for me with "widgetSort". With "widgetSortDirection" all is fine. Anyone else with this Bug?

### CODE REVIEW

**Comment by beatmasterRS** [comment]
I could not reproduce this behaviour. I have tested with movies - title, sort method -> title, sort direction -> desc (and asc). Maybe someone else can confirm?

**Comment by semool** [comment]
Test it with a widget of TV Channels or Programs from Addons Section.

**Comment by beatmasterRS** [comment]
I still can't reproduce this, unfortunately, even with your instructions. The result is always the same. Maybe someone else can reproduce it.

But of course I wonder how this can be explained code-wise, if you only rename the properties?

**Comment by semool** [comment]
Create a Widget like this (These are the created Lines from skinshortcuts properties.file [skin.arctic.zephyr.mod.properties]):
`['mainmenu', '0', 'widget', 'addon'],
 ['mainmenu', '0', 'widgetName', '10001'],
 ['mainmenu', '0', 'widgetType', 'program'],
 ['mainmenu', '0', 'widgetTarget', 'programs'],
 ['mainmenu', '0', 'widgetPath', 'addons://sources/executable/'],
 ['mainmenu', '0', 'widgetaspect', 'Square'],
 ['mainmenu', '0', 'widgetSortby', 'lastused'],
 ['mainmenu', '0', 'widgetSortDirection', 'descending'],`

This is working. Now change the "widgetSortDirection" to "widgetSort" and let skinshortcuts rebuild the menu.
Then the Sort Direction will not work.

**Comment by beatmasterRS** [comment]
Unfortunately, I still cannot reproduce this behavior. Can anyone help?

**Pull request closed without merging**
