### PR TITLE
[Views] enable more viewtypes for "videos" content

### PR DESCRIPTION
**Pull request by Nanomani**
thanks :)

### CODE REVIEW

**Review by beatmasterRS — CHANGES_REQUESTED** [review]
I am running into an issue:

Before:
screenshot01083

After:
screenshot01084

**Comment by Nanomani** [comment]
Arf.. I have try to do my best. It is hard to all verified. :S
Sorry for that. I take a look

**Comment by Nanomani** [comment]
I have remove some views.
when I enable 509 | 510 | 511 | 513 it breaks view "list" ???
views added : 53, 55, 56, 58, 515, 517, 519, 521

**Review by beatmasterRS — COMMENTED** [review]
Thank you.

To be honest, I have no idea, what this behaviour causes... 
I have checked the views you have mentioned, but I can't see a difference to views, where this is working...

**Comment by Nanomani** [comment]
It is strange. I have take lot time to try understand something too
But in this state the more useful views type are enable.
I m happy with that. I not need more. So you can merge if your are agree too :)

**Comment by beatmasterRS** [comment]
Could you please try to add the other ones? I have made a change, that seems to fix the issue:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/243/commits/7095fc2c6c54348c737acca368f13b745df7267a

**Comment by Nanomani** [comment]
views added : 501, 504, 507, 509, 510, 511, 512, 513, 514, 51, 522, 54, 59
all tested. all is fine nows. thanks :)

**Pull request merged**
