### PR TITLE
Use expression for audiocodec and hdr detection

### PR DESCRIPTION
**Pull request by fabricionaweb**
I think we can use expressions to reduce some duplicated code.

Im using the same conditional for ListItem + VideoPlayer, by my tests its fine. What do you think? 
Tell me if it is wrong 

Are we using the HUB thing? I dont know what is or how can I see... but there are some pieces of code that mention the `Container(9500)` and I assume that is for the Hub, I dont know how test it... looks like there are some outdated code there...

### CODE REVIEW

**Comment by fabricionaweb** [comment]
The documentation dont mention it, but I tested and the `opus` is native supported, we dont need manual conditional...

**Review by beatmasterRS — CHANGES_REQUESTED** [review]
There is an issue with your `String.Contains(ListItem.Filenameandpath) | String.Contains(Player.Filenameandpath)` condition:

When player is playing a hdr movie and focus in a movie list is on a non hdr-movie, the hdr flag is still shown, cause `String.Contains(Player.Filenameandpath)` is also true. You know, what i mean? :)

screenshot00452

screenshot00453

screenshot00454

**Comment by fabricionaweb** [comment]
Well notice, thanks! I tested the opposite (play a non hdr etc), but not this.

Could you see if its better now?

Do you agree we can test if `VideoPlayer.IsFullscreen` is true to test the `Player.FileNameAndPath`?

**Comment by fabricionaweb** [comment]
I have a thing here.... One of my movies is being detected as ATMOS in ListView but in OSD is TrueHD... 

Im looking....

**Review by beatmasterRS — APPROVED** [review]
Looks good! i haven't found any issues. 

Thanks for your work :)

**Pull request merged**
