### PR TITLE
Preshow integration

### PR DESCRIPTION
**Pull request by garzilla**
Split from prior pull request

PreShow skin integration - some parts might be outdated, but the implementation in the code is accurate. 

https://preshowexperience.com/skin-integration/

### CODE REVIEW

**Comment by garzilla** [comment]
i didn't put a toggle in the manage>settings menu because i feel if the user has preshow experience installed they would want it visible unless they disabled it in the kodi addon settings. 

preshow users would ultimately like a way to launch preshow with one click but that isn't easily attainable. i found the easiest path to launch preshow is for the user to set their playback to launch info instead of play.

the user focuses on the movie they want, presses select, info is now visible and the preshow button is in focus. Now the user can simply press select again to start the preshow experience. it's was a welcome addition for preshow users.

**Comment by garzilla** [comment]
was there anything else i need to do to this one? i added the buttons and fixed the items mentioned in the prior PR

thanks!

**Review by beatmasterRS — CHANGES_REQUESTED** [review]
>1080i/Includes.xml
- Button 490 needs a condition to enable/disable

>1080i/DialogVideoInfo.xml
- not need to check for System.HasAddon(script.preshowexperience) + System.AddonIsEnabled(script.preshowexperience). Only System.AddonIsEnabled(script.preshowexperience) + condition to enable/disable is needed
- if using a video addon and dialogvideoinfo opens, no button gets focused.

>1080i/Includes_Labels.xml
- localized strings must be used. Please use string id 31170 for that

**Comment by beatmasterRS** [comment]
https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/996

**Pull request closed without merging**
