### PR TITLE
[NowPlaying] focus controls instead main menu (2)

### PR DESCRIPTION
**Pull request by beatmasterRS**

### CODE REVIEW

**Comment by beatmasterRS** [comment]
I think i've found a better way to refocus the player controls then in https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/984

**Comment by beatmasterRS** [comment]
@Nanomani refocus should work fine to the player controls after 5 seconds, if player controls are visible. Works with all slide out settings. maybe you can take a look and test? :)

**Comment by Nanomani** [comment]
> @Nanomani refocus should work fine to the player controls after 5 seconds, if player controls are visible. Works with all slide out settings. maybe you can take a look and test? :)

Seems working like expected to me. Tested with "Vertical/modern Multi Widgets Netflix" :)

Just the new settings "only hide menu items" disable in all case with "Vertical Multi Widgets Netflix" but not with "modern Multi Widgets Netflix". 

Sorry but I don't see any difference what it must do with "modern Multi Widgets Netflix". :/

**Comment by beatmasterRS** [comment]
> > @Nanomani refocus should work fine to the player controls after 5 seconds, if player controls are visible. Works with all slide out settings. maybe you can take a look and test? :)
> 
> Seems working like expected to me. Tested with "Vertical/modern Multi Widgets Netflix" :)
> 
> Just the new settings "only hide menu items" disable in all case with "Vertical Multi Widgets Netflix" but not with "modern Multi Widgets Netflix".
> 
> Sorry but I don't see any difference what it must do with "modern Multi Widgets Netflix". :/

Thanks for testing :)

It is about hiding either the whole menu including the background or only the single menu items. This only affects the horizontal bottom menu, since this only has a background and date/time.

**Pull request merged**
