### PR TITLE
More Space for Furniture Flags

### PR DESCRIPTION
**Pull request by semool**
The last % is cutoff when all is displayed
Kodi_20210227_211158

### CODE REVIEW

**Comment by fabricionaweb** [comment]
It is even more complex... Because you can have the `bluray` the `web-dl` and if stars are not numeric....

**Comment by semool** [comment]
Yes some Icons are then not visible. But a cutoff looks not good.

**Comment by beatmasterRS** [comment]
Wenn all flags are enabled, like e.g. subtitles + subtitle-labels, some flags are no longer in the visible area. So in my opinion, this is simply not possible, because there will always be conditions, where some flags are not visible or only partially visible.

**Comment by semool** [comment]
Eventually we can add a auto scroll animation?

**Comment by semool** [comment]
Before:
before1
before2
After:
after1
after2

**Comment by beatmasterRS** [comment]
I close this issue, until a solution is found :)

**Pull request closed without merging**
