### PR TITLE
Add CJK Font

### PR DESCRIPTION
**Pull request by kuroehanako**
I Added CJK Font based on Ubuntu with NotoCJK Glyphs and works well.

screenshot00000
screenshot00001

### CODE REVIEW

**Comment by beatmasterRS** [comment]
Maybe you could adjust the linespace, that the text dows fit in the textboxes, e.g.: 

screenshot01199

screenshot01200

**Comment by kuroehanako** [comment]
I changed Spoqa Han Sans based font with Inter Latin glyphs. but, how to adjust linespace textbox?

screenshot00002

screenshot00004

**Comment by beatmasterRS** [comment]
You could use the linespace attribute, e.g.:

```
<font>
    <name>Tiny</name>
    <filename>InterCJKSC-Regular.ttf</filename>
    <size>26</size>
    <linespacing>1.06</linespacing>
</font>
```

Result:

screenshot01201

**Comment by beatmasterRS** [comment]
In some views the line spacing seems to be incorrect. I got better results with "1.07". Can you test this on your end?

**Comment by kuroehanako** [comment]
It works well.

screenshot00009

screenshot00010

**Comment by beatmasterRS** [comment]
Looks good in my eyes. Thanks for your work :)

**Pull request merged**
