### PR TITLE
[SkinSettings] logo added

### PR DESCRIPTION
**Pull request by Nanomani**
work is needed :D

### CODE REVIEW

**Comment by Nanomani** [comment]
You want perhaps a new settings for display or not the logo ?

**Comment by beatmasterRS** [comment]
I've looked at it again now and to be honest, I don't like it that much at this place/position. Unfortunately, I also have not found a better place. :D

I took a look to see where there was still space. The only place is probably this:

screenshot00116

But i have no idea, if this looks good or not :D

**Comment by Nanomani** [comment]
Your proposal is interesting only if the logo is displayed when you select "Skin" not "Benutzeroberfläche".

nevertheless why my PR ? it was not just to look pretty :D 
"skin-settings" and "kodi-settings are very similar now.
when you switch between the two very quickly it allows you to quickly identify which one is open.

4 possible options : 

1. that I stop the coffee
2. that I stop doing so many tests
3. close this PR and stop thinking about it
4. add an option in "extras" to display or not the logo

All this does not matter :) 
So feel free to close if you prefer.
No problem for me

**Comment by beatmasterRS** [comment]
:D 

Add an option in "extras" to display or not the logo is possible :)

**Comment by Nanomani** [comment]
I have finish.
minor adjustments are probably necessary.
but your skill started when mine stopped :D

**Comment by beatmasterRS** [comment]
Good work! i think its ready to get merged :)

**Comment by Nanomani** [comment]
> Good work! 

Thank you for your support :D 

> i think its ready to get merged

lets go :) 
Thanks again

**Pull request merged**
