### PR TITLE
Language strings testing search replace

### PR DESCRIPTION
**Pull request by Nanomani**
For testing only

 Cleaning strings.po :  DE, EN, FR

### CODE REVIEW

**Comment by Nanomani** [comment]
"script.shortcuts" don't like if I replace 37663 by 31156...
I don't understand why ?



If I reverse only  31156 by 37663 all is good

**Comment by beatmasterRS** [comment]
Have you forced a rebuild of the skin shortcuts config?

**Comment by Nanomani** [comment]
Yes :)
I delete "script-skinshortcuts-includes.xml" to be sure

**Comment by Nanomani** [comment]
Rollback of all 31xxx to 37xxx in powermenu.DATA.xml : 

- 31156 => 37663
- 31232 => 37703
- 31360 => 37814
- 31364 => 37818

**Comment by Nanomani** [comment]
Lot of noise for nothing, the cache on Windows 10 need to be purged.
All is ok :D

It ready for test : 
ZIP : https://github.com/Nanomani/skin.arctic.zephyr.mod/archive/refs/heads/language-strings-testing-search-replace.zip

So is all is okay for you 1 things must to be do to be perfect.
re-order from smallest ID strings to largest in all files strings.po ...

**Comment by Nanomani** [comment]
Definitely no revert ID string in powermenu.DATA.xml is necessary...
I don't know why. Anyway It can usefull you test all of this.

Files changed : 142  :D

ZIP : https://github.com/Nanomani/skin.arctic.zephyr.mod/archive/refs/heads/language-strings-testing-search-replace.zip

**Comment by beatmasterRS** [comment]
After changing strings in skinshortcuts files, make sure to foirce a rebuilt of the skinshortcuts (power)menu. You can change an item or reset to skin defaults to force that :)

**Comment by beatmasterRS** [comment]
Have you take a look at the script-skinshortcuts-includes.xml file? In this file there have to be the strings. Imho the file only got changed, if you make some changes to the (power)-menu.

**Comment by beatmasterRS** [comment]
>>EDIT : when this will be okay for you. I will post a new PR just to re-order all ID strings from less number to the bigger number in all files strings.po

thats okay :)

**Comment by beatmasterRS** [comment]
What i just wanted to say is, you can check in script-skinshortcuts-includes.xml file, if there are the correct new string id's or the old ones. There must be a reason for this... :)

**Comment by beatmasterRS** [comment]
Maybe you could provide the files in an other PR, where there is the issue with the skinshortcuts power menu? So i could test better.

**Comment by beatmasterRS** [comment]
Just testing with all your changes and id's:

31156
31232
31360
31364

and all works fine for me. Also in script-skinshortcuts-includes.xml there are the correct id's e.g.:

```
`<item id="11">
			<property name="id">$NUMBER[11]</property>
			<property name="mainmenuid">20</property>
			<label>$LOCALIZE[31156]</label>
			<label2>Power Menu Shortcut</label2>
			<icon>special://skin/extras/icons/addtile.png</icon>
			<thumb />
			<property name="labelID">31156</property>
			<property name="defaultID">31156</property>
			<visible>[System.Loggedon] + String.IsEqual(Container(300).ListItem.Property(submenuVisibility),powermenu)</visible>
			<onclick condition="Window.IsActive(DialogButtonMenu.xml)">Close</onclick>
			<onclick>ActivateWindowAndFocus(skinsettings,9108,2)</onclick>
			<property name="path">ActivateWindowAndFocus(skinsettings,9108,2)</property>
			<property name="list">9108</property>
			<visible>String.IsEqual(System.ProfileName,Master user)</visible>
			<property name="group">powermenu</property>
			<property name="isSubmenu">True</property>
		</item>`
```

**Comment by Nanomani** [comment]
> After changing strings in skinshortcuts files, make sure to foirce a rebuilt of the skinshortcuts (power)menu. You can change an item or reset to skin defaults to force that :)

I have already done all of this :)

> What i just wanted to say is, you can check in script-skinshortcuts-includes.xml file, if there are the correct new string id's or the old ones. There must be a reason for this... :)

you are completely right :).  script-skinshortcuts-includes.xml are regenerate with all old ID ones in powermenu.DATA.xml : 

37663 , 37703 , 37814 , 37818 
o_O

**Comment by beatmasterRS** [comment]
Try to reset the power menu to skin defaults

**Comment by Nanomani** [comment]
> Just testing with all your changes and id's:
> 
> 31156
> 31232
> 31360
> 31364
> 
> and all works fine for me. Also in script-skinshortcuts-includes.xml there are the correct id's e.g.:
> ```

If you restart Kodi, It is always fine ?

**Comment by beatmasterRS** [comment]
Also aftrer restarting kodi all is fine for me :)

If you reset to skin defaults, you should see instant after reset that on the left side, the items have to be back to standard config:

screenshot00012

screenshot00013

screenshot00015

**Comment by Nanomani** [comment]
Okay I got it. thanks :D 

If I all understand. My PR is good :) 
but a fix is necessary for "skinshortcuts" with rebuilding power menu ?

**Comment by beatmasterRS** [comment]
What I noticed: After the addon version is increased, SkinShortcuts automatically makes a rebuilt of the menus. So everything should work fine :)

**Comment by beatmasterRS** [comment]
But I think we will test it again intensively when you have everything ready :) With github,we can easily switch between versions/PR's :)

**Comment by Nanomani** [comment]
> But I think we will test it again intensively when you have everything ready :) With github,we can easily switch between versions/PR's :)

I have finish :  

- All strings ID are clean now everywhere.
- All strings unnecessary are delete
- msgctxt "#31000" to msgctxt "#31536" are used

the last things to do is a new PR just to re-order all ID strings from less number to the bigger number in all files strings.po.
You want this before merge ? I m right ?

**Comment by beatmasterRS** [comment]
Yes, good is, if we have a finished PR, where we can test all changes at once :)

Thanks a lot :)

**Comment by beatmasterRS** [comment]
Thanks for your hard work! :) I have had a first look and so far everything looks good for me :)

**Comment by Nanomani** [comment]
> Thanks for your hard work! :) I have to test ...

This PR was a big baby :D Sure take all time necessary. I must test too ...

**Comment by beatmasterRS** [comment]
includes_labels.xml, line 1375 `<value condition="Control.HasFocus(7) + String.IsEmpty(ListItem.UserRating)">$LOCALIZE[31532]</value>` points to "Use thumbnail instead of fanart", but i think that was my fault in a previous version. In master branch it also points to "Use thumbnail instead of fanart" :D

**Comment by Nanomani** [comment]
In the lastest master it is always this with old strings "38512"  :)

**Comment by beatmasterRS** [comment]
I will have a look at it, when I'm back from work :D

**Comment by beatmasterRS** [comment]
I havent found any other issues :) merge?

**Comment by Nanomani** [comment]
> I havent found any other issues :) 

Me too :)

> merge?

Lets go :D

**Comment by beatmasterRS** [comment]
:D

**Pull request merged**
