### PR TITLE
[Litebox] use litebox for blur

### PR DESCRIPTION
**Pull request by beatmasterRS**

### CODE REVIEW

**Comment by Nanomani** [comment]
Some improvement/fix are needeed

the preview sometimes shows a black screen : 

screenshot00005

The preview is in the background : 

screenshot00007

with "artist slideshow" it's weird : 

screenshot00008

this is the hot result of a very fast test : /

**Comment by beatmasterRS** [comment]
- I have had the same issue with the preview window, when pixelate is enabled. 
- For your now playing window, please disable "fullsize fanart"

I have made a few changes, please test :)

**Comment by beatmasterRS** [comment]
- A Kodi restart after made some changes, helped for me
- From the skin side, there is nothing more I can do imho
- Pixelate is mostly working well, after I had restarted Kodi

**Comment by beatmasterRS** [comment]
I have removed and changed some settings of litebox, so if you want to test, please make sure, to turn off and on, so the new standard settings for litebox are set.

**Comment by beatmasterRS** [comment]
So, after a few hours of testing, it seems, that litebox does somtimes not work properly. 
In userdata/skin.arctic.zephyr.mod/settings.xml all values are set correct.

- Sometimes if you close and reopen the blur-settings, litebox seems not to use the settings you have set. E.g. when using pixelate, the pixels are much smaller then the value, that is set.

I have made another testing branch. If you like, you can test:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/tree/litebox-support-2

- Please make sure, after switching to another branch/PR, that you disable and enable blur, so that all values are set correctly.

Over and out :D

**Comment by Nanomani** [comment]
> So, after a few hours of testing, it seems, that litebox does somtimes not work properly.
> In userdata/skin.arctic.zephyr.mod/settings.xml all values are set correct.
> 
> * Sometimes if you close and reopen the blur-settings, litebox seems not to use the settings you have set. E.g. when using pixelate, the pixels are much smaller then the value, that is set.
> 
> I have made another testing branch. If you like, you can test:
> 
> https://github.com/beatmasterRS/skin.arctic.zephyr.mod/tree/litebox-support-2
> 
> * Please make sure, after switching to another branch/PR, that you disable and enable blur, so that all values are set correctly.
> 
> Over and out :D


that reassures me ... I am not alone in having misunderstandings about the result. :D
I take my time this time

**Comment by Nanomani** [comment]
I thinks all works like expected now.

Not sure to use "Pixelate" (or "twotone") :D 
For a same setting the pixel size seems differente. 

This is not linked with Litebox. 
This is linked with the resolution of the fanart displayed.
the only solution is to have fanart of the same resolution for everything

Anyway everyone is free to appreciate the results like he want :)
For me you can push this PR now :)

**Comment by beatmasterRS** [comment]
For me, when changing pixelsize, sometimes litebox does nothing...

But after retarting kodi, all seems to be fine, with the new values, i had set

**Comment by Nanomani** [comment]
use "Pixelate" and navigate on each item on Widgets : 
sometime is good sometime pixel become bigger for the same item : /

**Comment by beatmasterRS** [comment]
I have also noticed that. And then after you restart kodi?

**Comment by Nanomani** [comment]
> I have also noticed that. And then after you restart kodi?

Yes after it is fine.

**Comment by beatmasterRS** [comment]
We just need to figure out what it could be first. :D For me it works even after a restart, so it could be the addon, I do not know....

**Comment by beatmasterRS** [comment]
Just now i have testet the colorbox script with AZ.2 pkscout mod and there seems also to be an issue, when settings are changed, and then i am click on previwe image. The new generated image doenst have the new values... i have to click on the changed value once more, to get the image with new values...

my english is terrible, sorry :D

**Comment by beatmasterRS** [comment]
i will ask in kodi forum

**Comment by Nanomani** [comment]
> my english is terrible, sorry :D

don't matter. I have understand :)
My english is the same :D

**Comment by beatmasterRS** [comment]
https://forum.kodi.tv/showthread.php?tid=363433&pid=3049747#pid3049747

**Comment by beatmasterRS** [comment]
After hours of testing, it _seems_ to work for me with this branch:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/tree/litebox-support-4

Please restart kodi, before testing. I have tested with pixelate:
- set pixelsize to 20, going to home menu, let litebox generate some images by scroll through widgets
- going to blur settings, set pixelsize to 10, going to home menu, let litebox generate some images by scroll through widgets

For me, there is no more the effect, we had noticed:

>>Sometimes using "Pixelate" and navigate on each item on Widgets: sometime is good, sometime pixel become very big for the same item

**Comment by Nanomani** [comment]
> After hours of testing, it _seems_ to work for me with this branch:
> 
> https://github.com/beatmasterRS/skin.arctic.zephyr.mod/tree/litebox-support-5
> 
> What I noticed is,
> 
> * that everything works fine when Kodi was restarted and blur was already enabled.
> * That is, the litebox script is started by the startup.xml
> * Changes at pixelate are thus possible for me without problems

I confirm all this


> I think if you start the addon twice, that is by enabling/disabling the blur function in the skin settings, it will cause errors.
> 
> Therefore I have removed this code. [643764f](https://github.com/beatmasterRS/skin.arctic.zephyr.mod/commit/643764f458a5e6e0880cfff164956668a5da2c40)
> 
> Litebox generates images only, if the image control 7975 is visible.
> 
> For me, there is no more the effect, we had noticed:
> 
> > > Sometimes using "Pixelate" and navigate on each item on Widgets: sometime is good, sometime pixel become very big for the same item


Yes everything works fine now if we restart kodi as you described it

> Again i hav to say: thanks for your help, with testing and all you have done! :)

thank you especially for all your work. And if I can help a little, it's good :)

> Maybe we can run this addon at startup in general, if this script only does its work, when the image control 7975 is visible, but i have to ask that in the forum, to be sure :)

if I understood everything correctly there are only benefits to running it at startup ? Right ?

**Comment by beatmasterRS** [comment]
I think the problems were caused by running the script twice, by having it already running and re-enabling it in the skin settings. By the way, this is how it ran in AZ - leia mod and in AZ 2 with colorbox without problems. 

Have a look at this branch, you can see the comments, what i have changed now. 

if this also works, everything is fine and we have a good user experience, means that no restart is required, after enable the setting

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/tree/litebox-support-6

**Comment by beatmasterRS** [comment]
>>if I understood everything correctly there are only benefits to running it at startup ? Right ?

Yes, if it doesn't take up resources. :) But still not a great solution to run a script that you don't use if you don't have Blur enabled :D

Maybe the litebox-support-6 branch works also well for you. With that, no restart is required and the user can enable/disable the setting without problems. The litebox script will not be startet twice, scince its stopped first, as you can see in the comments at the code.

**Comment by Nanomani** [comment]
> my first tests are looking good _so far_... :D

your hard work paid off :)
all works like charm for me too 

Off topic (just for information) : 

"try to lock skin colors/themes/fonts" is enable in my side.
after each update fonts and colours is reset to their default value

screenshot00022

**Comment by beatmasterRS** [comment]
I have made a busy loader animation, so if disable/enable litebox in skin settings, litebox has enough time to start, before you can enter litebox settings. 
Because when you enter litebox settings to fast after enable, it is possible, that litebox doesn't show correctly, cause its not running properly.

https://youtu.be/RptCwE_2rH8

**Comment by Nanomani** [comment]
This PR is ready to merge now ?  :)

**Comment by beatmasterRS** [comment]
Yes, will be merged in a moment :)

**Comment by beatmasterRS** [comment]
I thought about changing the skin settings option "blur-settings / enable blur" to "effect-settings / enable effects" or something like that, scince it's now not just a setting for blur. What do you think?

**Comment by Nanomani** [comment]
I completely agree  👍 

just suggestion. I don't know... :)
 
EFFECT-SETTINGS
enable blur / twotone / pixelate

**Pull request merged**
