### PR TITLE
[CoreElec] design fit to AZR - part2

### PR DESCRIPTION
**Pull request by Nanomani**

### CODE REVIEW

**Comment by beatmasterRS** [comment]
Looks good so far, but there is a difference in code:

After line 451, there are two more icons in original xml:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/52baac73c086edc053ed2a75e9be757ecdef8c4e/1080i/service-CoreELEC-Settings-mainWindow.xml#L515-L533

Could you have a look at this? :)

**Comment by beatmasterRS** [comment]
And please have a look at the icons positions: one of this has a bottom position:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/53ce646b6c5d3c168780d2d55fe72fd51c605735/1080i/service-CoreELEC-Settings-mainWindow.xml#L551-L570

screenshot00031
screenshot00033

**Comment by beatmasterRS** [comment]
VPN icon is missing:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/52baac73c086edc053ed2a75e9be757ecdef8c4e/1080i/service-CoreELEC-Settings-mainWindow.xml#L395-L404

Truste's icon is missing, also on other lines:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/52baac73c086edc053ed2a75e9be757ecdef8c4e/1080i/service-CoreELEC-Settings-mainWindow.xml#L891-L900

**Comment by beatmasterRS** [comment]
Thanks :)

**Comment by Nanomani** [comment]
well well I can do all of that : 
- VPN not a problem
- icons vertical vs icons horizontal not a problem if you prefer :D 
- unlock.png and key.png are gadgets that do not add anything. But why not :)

**Comment by Nanomani** [comment]
Please see the change here : https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/358

**Comment by Nanomani** [comment]
- [ X ] VPN
- [ X ] icons vertical vs icons horizontal 
- [ X ] unlock.png and key.png restored

**Comment by beatmasterRS** [comment]
Looks good! Is it ready to merge?

**Comment by Nanomani** [comment]
In my side I do my best so if you are happy :)
let go for merge :D

**Pull request merged**
