### PR TITLE
[DialogVideoInfo] improvement, button "this year" added

### PR DESCRIPTION
**Pull request by Nanomani**
A new button "this year" is added in  Video Information Dialog

This mean that if this button is enable in VideoDialogSettings you can : 
- have movies/ TVshows list same year of item opened with Video Information Dialog

This works with 
- "only local information" enable / disable
- Movies / TV Shows

### CODE REVIEW

**Comment by beatmasterRS** [comment]
Will unfortunately not be added, because I try to keep the skin lightweight and in this case, I don't think "by year" has the same importance as "by director" or "similar".

**Comment by Nanomani** [comment]
seriously? This is really very bad news. this is probably my top 3 PR that I wanted to save.

It is an educational tool for me when I share the story of a film with others in the context of a specific year.

It really is an important feature for me. wow that's a shame :(

**Comment by Nanomani** [comment]
@beatmasterRS 
You sincerely underestimate the interest of this. 
It is the same importance and complementary to "Director" and "similar".
And much more useful than "studio"

I can't change anything of course. but I really hope you can reverse your decision.
In any case, I will keep it on my side. I use it every day. 
I can't do without it anymore with these one too :  
#582 and #602 

It's a shame about this one too : #508
It was very promising it would have been a major part to make your skin more perfect.
And add "Year" in search result would have been perfect... :)

So All this has calmed my enthusiasm 
I will not bother you much in the future. 
You are too tough in business for me :D

**Comment by beatmasterRS** [comment]
Okay, "By year" would be okay, but the "animation only" option - imho this is not very consistent in relation to the other extended lists and not an option i would like to have...

**Comment by Nanomani** [comment]
When you have playlists for kid and other for parent this option make sens.
When you have a huge library with lot of cartoon/animation and lot of movies this option make sens
You don't want to have together cartoon and horror movies in same list for the kid. 

So I have already thinking about it for not make a sub setting.
I can make this setting global at end of "infovideodialogsetting" : 

"prefer local information only"
"separate cartoon / movie in list"

This mean works with "This year" and "Director"
"Similar" works very well without a such setting

Some director have make movies and cartoon/animation
e.g. : Tim Burton, Robert Zemeckis

If not possible to keep this settings "separate cartoon / movie in list". 
So you are rigth. the list from "This year" will be for some user and for me too confuse and not friendly for kid.
It better to close this PR in this case.

**Pull request closed without merging**
