### PR TITLE
[Home Vertical] Hide completely menu when slide out

### PR DESCRIPTION
**Pull request by Nanomani**
Hide completely menu for Vertical like Modern when slide out

### CODE REVIEW

**Comment by Nanomani** [comment]
See https://github.com/beatmasterRS/skin.arctic.zephyr.mod/issues/423

I don't use setting "More clean & minimal" already used for "modern layout".
I thinks this PR is most a fix. This PR change a very tiny thing.

This mean the menu for Vertical Layout  is hidden consistently with Modern Layout when slide out 
If your are not agree so ping me. I will add the option

**Comment by Nanomani** [comment]
I m stupide. I know the answer :D  
I add the option ... :)

**Comment by beatmasterRS** [comment]
Sounds good :D

**Comment by beatmasterRS** [comment]
Will be merged soon :)

**Pull request merged**
